### ISSUE TITLE
Bug in Organization Mapping Documentation

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath.github.io#208]
http://docs.stormpath.com/rest/product-guide/#adding-an-account-store-to-an-organization

>To create an Organization Account Store Mapping, you need to collection a Directory or Group href and the organization’s href. You can create a mapping by POSTing a new AccountStoreMapping resource to the /v1/accountStoreMappings URI. You must specify the application and the account store via their respective hrefs.

You need to specify the *organization* and the account store -- not the *application*.

**Comment by omgitstom** [comment]
Closing, this is fixed in the new rest guide
