### ISSUE TITLE
Java SDK Appendix should skip Tests when building

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath.github.io#219]
http://docs.stormpath.com/java/product-guide/#appendix

- Current bullet 2 should be bullet 3. It should be changed: `mvn clean install` should be `mvn clean install -DskipTests=true`

- A new bullet 2 should be: `cd stormpath-sdk-java`

- Bullet 4 should include the following text:
Here you will find a list of all the runtime dependencies necessary for the module. In addition to the jars under `extensions/httpclient/target/dependency` directory you will also need the actual module's jar located in the parent dir: `extensions/httpclient/target`.

**Comment by rdegges** [comment]
I'm closing this as these docs are generated by the Java SDK now. So ya'll can freely update them at any time in the java sdk repo.
