### ISSUE TITLE
Looks like in typo in the <br> element when resetting password

### ISSUE THREAD

**Issue by mbigras** [stormpath/stormpath.github.io#272]
I'm not sure if this is the right spot for this, so please let me know if I should be opening this issue somewhere else, or sending support an email, but I noticed there seems to be a typo in the `<br>` element when resetting your password from the main [Stormpath](https://stormpath.com/) site. See picture below :) 
![](https://cl.ly/453Q1U0Y002R/Screen%20Shot%202016-07-22%20at%207.10.49%20AM.png)

**Comment by robertjd** [comment]
This code is in another repo, but we have merged in a fix for it and you should see this soon.  Thanks!
